// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Blocks        string
	Friends       string
	Subscriptions string
	Users         string
}{
	Blocks:        "blocks",
	Friends:       "friends",
	Subscriptions: "subscriptions",
	Users:         "users",
}
