// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFriendships(t *testing.T) {
	t.Parallel()

	query := Friendships()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFriendshipsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFriendshipsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Friendships().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFriendshipsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FriendshipSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFriendshipsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FriendshipExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Friendship exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FriendshipExists to return true, but got false.")
	}
}

func testFriendshipsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	friendshipFound, err := FindFriendship(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if friendshipFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFriendshipsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Friendships().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFriendshipsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Friendships().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFriendshipsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	friendshipOne := &Friendship{}
	friendshipTwo := &Friendship{}
	if err = randomize.Struct(seed, friendshipOne, friendshipDBTypes, false, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}
	if err = randomize.Struct(seed, friendshipTwo, friendshipDBTypes, false, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = friendshipOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = friendshipTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Friendships().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFriendshipsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	friendshipOne := &Friendship{}
	friendshipTwo := &Friendship{}
	if err = randomize.Struct(seed, friendshipOne, friendshipDBTypes, false, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}
	if err = randomize.Struct(seed, friendshipTwo, friendshipDBTypes, false, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = friendshipOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = friendshipTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func friendshipBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func friendshipAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Friendship) error {
	*o = Friendship{}
	return nil
}

func testFriendshipsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Friendship{}
	o := &Friendship{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, friendshipDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Friendship object: %s", err)
	}

	AddFriendshipHook(boil.BeforeInsertHook, friendshipBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	friendshipBeforeInsertHooks = []FriendshipHook{}

	AddFriendshipHook(boil.AfterInsertHook, friendshipAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	friendshipAfterInsertHooks = []FriendshipHook{}

	AddFriendshipHook(boil.AfterSelectHook, friendshipAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	friendshipAfterSelectHooks = []FriendshipHook{}

	AddFriendshipHook(boil.BeforeUpdateHook, friendshipBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	friendshipBeforeUpdateHooks = []FriendshipHook{}

	AddFriendshipHook(boil.AfterUpdateHook, friendshipAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	friendshipAfterUpdateHooks = []FriendshipHook{}

	AddFriendshipHook(boil.BeforeDeleteHook, friendshipBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	friendshipBeforeDeleteHooks = []FriendshipHook{}

	AddFriendshipHook(boil.AfterDeleteHook, friendshipAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	friendshipAfterDeleteHooks = []FriendshipHook{}

	AddFriendshipHook(boil.BeforeUpsertHook, friendshipBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	friendshipBeforeUpsertHooks = []FriendshipHook{}

	AddFriendshipHook(boil.AfterUpsertHook, friendshipAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	friendshipAfterUpsertHooks = []FriendshipHook{}
}

func testFriendshipsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFriendshipsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(friendshipPrimaryKeyColumns, friendshipColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFriendshipToOneUserUsingUser1(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Friendship
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.User1ID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User1().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := FriendshipSlice{&local}
	if err = local.L.LoadUser1(ctx, tx, false, (*[]*Friendship)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User1 == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User1 = nil
	if err = local.L.LoadUser1(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User1 == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testFriendshipToOneUserUsingUser2(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Friendship
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.User2ID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User2().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := FriendshipSlice{&local}
	if err = local.L.LoadUser2(ctx, tx, false, (*[]*Friendship)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User2 == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User2 = nil
	if err = local.L.LoadUser2(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User2 == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testFriendshipToOneSetOpUserUsingUser1(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Friendship
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, friendshipDBTypes, false, strmangle.SetComplement(friendshipPrimaryKeyColumns, friendshipColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser1(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User1 != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.User1Friendships[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.User1ID, x.ID) {
			t.Error("foreign key was wrong value", a.User1ID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.User1ID))
		reflect.Indirect(reflect.ValueOf(&a.User1ID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.User1ID, x.ID) {
			t.Error("foreign key was wrong value", a.User1ID, x.ID)
		}
	}
}

func testFriendshipToOneRemoveOpUserUsingUser1(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Friendship
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, friendshipDBTypes, false, strmangle.SetComplement(friendshipPrimaryKeyColumns, friendshipColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser1(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser1(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User1().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User1 != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.User1ID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.User1Friendships) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testFriendshipToOneSetOpUserUsingUser2(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Friendship
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, friendshipDBTypes, false, strmangle.SetComplement(friendshipPrimaryKeyColumns, friendshipColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser2(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User2 != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.User2Friendships[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.User2ID, x.ID) {
			t.Error("foreign key was wrong value", a.User2ID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.User2ID))
		reflect.Indirect(reflect.ValueOf(&a.User2ID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.User2ID, x.ID) {
			t.Error("foreign key was wrong value", a.User2ID, x.ID)
		}
	}
}

func testFriendshipToOneRemoveOpUserUsingUser2(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Friendship
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, friendshipDBTypes, false, strmangle.SetComplement(friendshipPrimaryKeyColumns, friendshipColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser2(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser2(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User2().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User2 != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.User2ID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.User2Friendships) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testFriendshipsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFriendshipsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FriendshipSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFriendshipsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Friendships().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	friendshipDBTypes = map[string]string{`ID`: `integer`, `User1ID`: `integer`, `User2ID`: `integer`}
	_                 = bytes.MinRead
)

func testFriendshipsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(friendshipPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(friendshipAllColumns) == len(friendshipPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFriendshipsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(friendshipAllColumns) == len(friendshipPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Friendship{}
	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, friendshipDBTypes, true, friendshipPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(friendshipAllColumns, friendshipPrimaryKeyColumns) {
		fields = friendshipAllColumns
	} else {
		fields = strmangle.SetComplement(
			friendshipAllColumns,
			friendshipPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FriendshipSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFriendshipsUpsert(t *testing.T) {
	t.Parallel()

	if len(friendshipAllColumns) == len(friendshipPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Friendship{}
	if err = randomize.Struct(seed, &o, friendshipDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Friendship: %s", err)
	}

	count, err := Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, friendshipDBTypes, false, friendshipPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Friendship struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Friendship: %s", err)
	}

	count, err = Friendships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
